version: '3.8'
services:
  gateway:
    build: gateway/
    image: shareit-gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:9090

  server:
    build: server/
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/shareit
      - DB_USERNAME=test
      - DB_PASSWORD=test

  db:
    image: postgres
    container_name: shareit-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test